version: "3"
networks:
  ip28:
    ipam:
      config:
        - subnet: 172.28.0.0/24
services:
  mybot:
    build: .
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    container_name: mybot
    networks:
      ip28:
        ipv4_address: 172.28.0.2
    restart: unless-stopped
